#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Issei Kimura
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
ans1 = 1
asn2 = 0
for line in sys.stdin:
    try:
        ans += int(line)
        ans1 *= int(line)
    except:
        ans += float(line)
        ans1 *= float(line)

ans2 = ans + ans1

print(ans, ans1, ans2)
